{"name": "test_failure", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "def test_failure():\n        \"\"\"this test fails\"\"\"\n>       assert False\nE       assert False\n\nallure_demo1.py:10: AssertionError"}, "description": "this test fails", "start": 1655274598024, "stop": 1655274598024, "uuid": "6465f6f6-6fc5-4489-9eab-ad11a8abaa07", "historyId": "4ecf26dfb4dcf3da4442fd110e068614", "testCaseId": "fb6d5dbad21c87a9f850ae9324b6d057", "fullName": "allure_demo1#test_failure", "labels": [{"name": "suite", "value": "allure_demo1"}, {"name": "host", "value": "MacBook-Pro-6.local"}, {"name": "thread", "value": "19317-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "allure_demo1"}]}